### ISSUE TITLE
Example 201-rusty-hello-world does not work

### ISSUE THREAD

**Issue by mrceperka** [rask/php-ffi-examples#1]
Hi there :wave:.

Thanks for the examples. I am aware of that this one might not be complete, because there is no blog post about it :)

I've been trying to do the same (rust -> generate headers, use `.h` and `.so`), but I've always ended up with an error. But then I've found your example and it also does not work (on my machine :D)

The error says: 
```
Fatal error: Uncaught FFI\Exception: Failed loading '/var/docker/target/debug/libmy_library.so' in /var/docker/hello.php:5
Stack trace:
#0 /var/docker/hello.php(5): FFI::cdef('#define FFI_LIB...', '/var/docker/tar...')
#1 {main}
  thrown in /var/docker/hello.php on line 5
```

Do you have any idea why does the error occur?
`php -m` show correctly ffi module and `php -v` show me, that `ffi.enable=true`

:pray: Thanks for your time and examples.

---
I'm using php alpine docker image, with enabled ffi.

```Dockerfile
#Dockerfile
FROM php:7.4.0-fpm-alpine
RUN set -e; \
    apk update; \
    apk add libffi-dev; \
    docker-php-ext-configure ffi; \
    docker-php-ext-install -j$(nproc) ffi pcntl
COPY ./php.ini /usr/local/etc/php/php.ini
```

```ini
;php.ini
ffi.enable=true
```

**Comment by mrceperka** [comment]
I've switched from `alpine` to `php:7.4.1-fpm-buster` and it helped :)

**Comment by rask** [comment]
Hello.

I see, might need to check out if that `alpine` images have problems with FFI in general, in case there is a bug or limitation that prevents FFI from running "properly".

Glad you got it working! I'm working on the second part right now but posted the example code publicly a bit earlier just to get something out as I've been a little busy with other stuff. :)
